### PR TITLE
feat: add array operators

### PR DESCRIPTION
**Pull request by afilp**
More info here: https://github.com/nestjsx/crud/pull/754

### CODE REVIEW

**Comment by zaro** [comment]
@afilp  unfortunately tests are failing with this change. I spend some time trying to figure out what causes it, but it's not obvious at all.

I don't have time in the next few days to figure it out, so it will have to wait until I have time...

**Comment by afilp** [comment]
Sure!

I just copied/pasted the old code from that PR:
https://github.com/nestjsx/crud/pull/754

So, that you can have a start. Most likely that old code would fail somewhere.

**Comment by zaro** [comment]
@afilp this is merged and released as 5.3.1 .

**Comment by afilp** [comment]
@afilp Does it work eventually? Without any changes?

**Comment by zaro** [comment]
@afilp  I don't understand do you mean?

Install v5.3.1 and check if it's working. I fixed the tests, but I didn't have time to test the two new array operators. The branch is actually meged, but I closed the PR, because it was way more work to merge it trough the PR. 

As for the changes, I had to make a trivial change because of small refractor that this PR is doing.

**Pull request closed without merging**
